# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: danmu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x61nmu.proto\x12 bilibili.community.service.dm.v1\"\xde\x02\n\x0b\x44\x61nmakuElem\x12\r\n\x05stime\x18\x02 \x01(\x05\x12\x0c\n\x04mode\x18\x03 \x01(\x05\x12\x0c\n\x04size\x18\x04 \x01(\x05\x12\r\n\x05\x63olor\x18\x05 \x01(\r\x12\r\n\x05uhash\x18\x06 \x01(\t\x12\x0c\n\x04text\x18\x07 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x08 \x01(\x03\x12\x0e\n\x06weight\x18\t \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\n \x01(\t\x12\x0c\n\x04pool\x18\x0b \x01(\x05\x12\x0c\n\x04\x64mid\x18\x0c \x01(\t\x12\x0c\n\x04\x61ttr\x18\r \x01(\x05\x12\x11\n\tanimation\x18\x16 \x01(\t\x12\x42\n\x08\x63olorful\x18\x18 \x01(\x0e\x32\x30.bilibili.community.service.dm.v1.DmColorfulType\x12\x0b\n\x03oid\x18\x1a \x01(\x03\x12<\n\x06\x64mFrom\x18\x1b \x01(\x0e\x32,.bilibili.community.service.dm.v1.DmFromType\"\x93\x01\n\x10\x44mSegMobileReply\x12<\n\x05\x65lems\x18\x01 \x03(\x0b\x32-.bilibili.community.service.dm.v1.DanmakuElem\x12\x41\n\x0b\x63olorfulSrc\x18\x05 \x03(\x0b\x32,.bilibili.community.service.dm.v1.DmColorful\"Y\n\nDmColorful\x12>\n\x04type\x18\x01 \x01(\x0e\x32\x30.bilibili.community.service.dm.v1.DmColorfulType\x12\x0b\n\x03src\x18\x02 \x01(\t*5\n\x0e\x44mColorfulType\x12\x0c\n\x08NoneType\x10\x00\x12\x15\n\x0fVipGradualColor\x10\xe1\xd4\x03*P\n\nDmFromType\x12\x11\n\rDmFromUnknown\x10\x00\x12\x10\n\x0c\x44mFromNormal\x10\x01\x12\r\n\tDmFromCmd\x10\x02\x12\x0e\n\nDmFromLive\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'danmu_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DMCOLORFULTYPE._serialized_start=643
  _DMCOLORFULTYPE._serialized_end=696
  _DMFROMTYPE._serialized_start=698
  _DMFROMTYPE._serialized_end=778
  _DANMAKUELEM._serialized_start=50
  _DANMAKUELEM._serialized_end=400
  _DMSEGMOBILEREPLY._serialized_start=403
  _DMSEGMOBILEREPLY._serialized_end=550
  _DMCOLORFUL._serialized_start=552
  _DMCOLORFUL._serialized_end=641
# @@protoc_insertion_point(module_scope) 