# Generated by Django 5.2 on 2025-04-16 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('danmaku_crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_start', models.FloatField(verbose_name='片段开始时间(秒)')),
                ('segment_end', models.FloatField(verbose_name='片段结束时间(秒)')),
                ('sentiment', models.CharField(choices=[('positive', '积极'), ('neutral', '中性'), ('negative', '消极')], max_length=10, verbose_name='情感倾向')),
                ('score', models.FloatField(verbose_name='情感得分')),
                ('danmaku_count', models.IntegerField(verbose_name='弹幕数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='danmaku_crawler.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '情感分析',
                'verbose_name_plural': '情感分析',
                'ordering': ['segment_start'],
            },
        ),
        migrations.CreateModel(
            name='DanmakuAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('sentiment', '情感分析'), ('keyword', '关键词分析'), ('timeline', '时间线分析'), ('user', '用户分析'), ('custom', '自定义分析')], max_length=20, verbose_name='分析类型')),
                ('result_json', models.JSONField(verbose_name='分析结果JSON')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='danmaku_crawler.video', verbose_name='分析视频')),
            ],
            options={
                'verbose_name': '弹幕分析',
                'verbose_name_plural': '弹幕分析',
                'ordering': ['-created_at'],
                'unique_together': {('video', 'analysis_type')},
            },
        ),
        migrations.CreateModel(
            name='KeywordExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='关键词')),
                ('weight', models.FloatField(verbose_name='权重')),
                ('frequency', models.IntegerField(verbose_name='出现频率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='danmaku_crawler.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '关键词提取',
                'verbose_name_plural': '关键词提取',
                'ordering': ['-weight'],
                'unique_together': {('video', 'keyword')},
            },
        ),
    ]
