# Generated by Django 5.2 on 2025-04-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danmaku_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='video',
        ),
        migrations.DeleteModel(
            name='KeywordExtraction',
        ),
        migrations.DeleteModel(
            name='SentimentAnalysis',
        ),
    ]
