# Generated by Django 5.2 on 2025-04-16 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvid', models.CharField(max_length=20, unique=True, verbose_name='BV号')),
                ('aid', models.BigIntegerField(blank=True, null=True, verbose_name='AV号')),
                ('title', models.CharField(max_length=200, verbose_name='视频标题')),
                ('owner', models.CharField(max_length=100, verbose_name='UP主')),
                ('owner_mid', models.BigIntegerField(blank=True, null=True, verbose_name='UP主ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('duration', models.IntegerField(default=0, verbose_name='视频时长(秒)')),
                ('last_crawled', models.DateTimeField(blank=True, null=True, verbose_name='上次爬取时间')),
            ],
            options={
                'verbose_name': '视频信息',
                'verbose_name_plural': '视频信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '进行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('danmaku_count', models.IntegerField(default=0, verbose_name='爬取弹幕数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_tasks', to='danmaku_crawler.video', verbose_name='目标视频')),
            ],
            options={
                'verbose_name': '爬取任务',
                'verbose_name_plural': '爬取任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Danmaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmid', models.BigIntegerField(unique=True, verbose_name='弹幕ID')),
                ('content', models.TextField(verbose_name='弹幕内容')),
                ('send_time', models.DateTimeField(verbose_name='发送时间')),
                ('progress', models.FloatField(verbose_name='视频进度(秒)')),
                ('mode', models.IntegerField(default=1, verbose_name='弹幕模式')),
                ('font_size', models.IntegerField(default=25, verbose_name='字体大小')),
                ('color', models.CharField(default='16777215', max_length=10, verbose_name='弹幕颜色')),
                ('user_hash', models.CharField(max_length=32, verbose_name='用户哈希')),
                ('weight', models.IntegerField(default=10, verbose_name='弹幕权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danmakus', to='danmaku_crawler.video', verbose_name='所属视频')),
            ],
            options={
                'verbose_name': '弹幕数据',
                'verbose_name_plural': '弹幕数据',
                'ordering': ['progress'],
                'indexes': [models.Index(fields=['video', 'progress'], name='danmaku_cra_video_i_ae1814_idx'), models.Index(fields=['send_time'], name='danmaku_cra_send_ti_2f0230_idx')],
            },
        ),
    ]
