# Generated by Django 5.2 on 2025-04-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danmaku_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='danmaku',
            name='page_duration',
            field=models.IntegerField(default=0, verbose_name='分P时长(秒)'),
        ),
        migrations.AddField(
            model_name='danmaku',
            name='page_id',
            field=models.IntegerField(default=1, verbose_name='分P编号'),
        ),
        migrations.AddIndex(
            model_name='danmaku',
            index=models.Index(fields=['page_id'], name='danmaku_cra_page_id_d60f72_idx'),
        ),
    ]
