# Generated by Django 5.2 on 2025-04-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danmaku_crawler', '0002_danmaku_page_duration_danmaku_page_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danmaku',
            name='progress',
            field=models.FloatField(verbose_name='视频进度(毫秒)'),
        ),
    ]
