# Generated by Django 5.2 on 2025-04-19 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danmaku_crawler', '0004_crawltask_user_video_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='bvid',
            field=models.CharField(max_length=20, verbose_name='BV号'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('bvid', 'user')},
        ),
    ]
