# Generated by Django 5.2 on 2025-04-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danmaku_crawler', '0005_alter_video_bvid_alter_video_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='danmaku_count',
            field=models.IntegerField(default=0, verbose_name='爬取弹幕数'),
        ),
    ]
